### ISSUE TITLE
feature request: exclude current repo's license

### ISSUE THREAD

**Issue by yen-tt** [TobyAndToby/generate-license-file#12]
Hello,
I have been using generate-license-file library to create third-party notices file for dependencies from repo's package.json and noticed that the generated file also include the repo's own license. Is it possible to add a feature flag to the CLI to not include your current package's license? Or potentially export things like the License class and/or format functions and variables from the library to assist this use case?
Thank you for your time!

**Comment by tobysmith568** [comment]
Hey @yen-tt - Thanks for raising this, we merged a PR into our main branch today to address this issue.
We plan to release a new minor version to npm within the next few days, so hopefully you should get the fix soon!

**Comment by yen-tt** [comment]
awesome! thank you

**Comment by tobysmith568** [comment]
Hey, sorry this took so long - the holiday season and whatnot got in the way. This should be fixed in version 1.3.0 which has now been released.

I'll close this issue now but if you're still finding any problems feel free to raise them with us and we'll see what we can do - thanks!
