### ISSUE TITLE
[Feature Request] Support links for replace config

### ISSUE THREAD

**Issue by alyoung1621** [TobyAndToby/generate-license-file#422]
I would like to request the ability to specify a URL to pull the license file using the [replace option](https://generate-license-file.js.org/docs/cli/config-file#replace) in the docs. This would be more convenient instead of having to download the license file and specify the path.

**Comment by tobysmith568** [comment]
Hey @alyoung1621 ,

Sorry we didn't reply to you sooner.
We've released this feature today in version 3.5.0.

Closed in #440
