### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by Hypercubed** [TobyAndToby/generate-license-file#477]
Running `generate-license-file` via `npx` fails with the error `Error: Cannot find module 'commander'`.  Looks like `@commander-js/extra-typings` has `commander` as a peer dep, but `generate-license-file` does not sepecify `commander` as a direct dep.

I'm guessing the fix as as simple as adding `commander` as a dep to `generate-license-file`'s `package.json`.

**Comment by tobysmith568** [comment]
Hey @Hypercubed ,

Thank you for raising this. I have a PR raised for it now - we'll get it merged and released asap

**Comment by tobysmith568** [comment]
This has been released in version 3.5.1
