### ISSUE TITLE
[Feature Request]: allow to retrieve only the license type

### ISSUE THREAD

**Issue by jfayot** [TobyAndToby/generate-license-file#487]
Is there any way to get only the license type (MIT, Apache-2.0, ISC...) instead of the full license text without parsing ?

**Comment by tobybessant** [comment]
Hey @jfayot,

Thanks for contributing to the discussion for this package.

This is not a feature we currently support. Please could you elaborate on what exactly the use case of this feature would be? I've included some questions below that might help explore this.

- How are you using generate-license-file (CLI or library)?
- Is there a technical requirement you’re trying to meet?
- Or a legal requirement you’re constrained by?

Many thanks,
Toby

**Comment by tobybessant** [comment]
Hey @jfayot,

For us to provide the license name or SPDX identifier for a license (either in the content itself or as additional data) we would need to be guessing based on what we _think_ the license file contains. While some websites and tools provide this functionality (even GitHub do it), it something we're not willing to do as we'd prefer to rely on what the package authors have explicitly declared.

Many thanks,

Toby
