### ISSUE TITLE
[Feature Request]: specify recursive dependency level

### ISSUE THREAD

**Issue by jfayot** [TobyAndToby/generate-license-file#488]
Is there any way to specify the recursive dependency level at which the generate-license-file will stop searching ?

**Comment by tobybessant** [comment]
Hey @jfayot,

Thanks for contributing to the discussion for this package.

This is not a feature we currently support. Please could you elaborate on what exactly the use case of this feature would be? I've included some questions below that might help clarify this.

- How are you using generate-license-file (CLI or library)?
- Is there a technical requirement you’re trying to meet?
- Or a legal requirement you’re constrained by?

Many thanks,
Toby

**Comment by tobysmith568** [comment]
Hey @jfayot,

As @tobybessant mentioned, this isn't something we currently support and at this moment it's not something we're looking to add unless there's justification for how it can help someone generate a license file while remaining compliant with _all_ their dependencies.

Feel free to reply/re-open if that's something you can follow up with.

Thanks
