### ISSUE TITLE
Inject license text if it is missing

### ISSUE THREAD

**Issue by jayvdb** [TobyAndToby/generate-license-file#525]
**How are you using generate-license-file?**
Library

**Is your feature request related to a problem? Please describe.**
We have a lot of dependencies that dont have a license text.  My guess is that the dependency defines the license in package.json, but the LICENSE file is missing or couldnt be found.

**Describe the solution you'd like**
Add the default license text of the specified license, which can be obtained from e.g. https://www.npmjs.com/package/spdx-license-list

**Additional context**

List of deps where the license text is just the license spdx identifier

```
@internationalized/date@3.5.6, @internationalized/message@3.1.5, @internationalized/number@3.5.4, @internationalized/string@3.2.4, @react-aria/i18n@3.12.3, @react-aria/label@3.7.12, @react-aria/live-announcer@3.4.0, @react-aria/meter@3.4.17, @react-aria/progress@3.4.17, @react-aria/separator@3.4.3, @react-aria/spinbutton@3.6.9, @react-aria/ssr@3.9.6, @react-aria/utils@3.25.3, @react-stately/calendar@3.5.5, @react-stately/checkbox@3.6.9, @react-stately/collections@3.11.0, @react-stately/color@3.8.0, @react-stately/combobox@3.10.0, @react-stately/datepicker@3.10.3, @react-stately/dnd@3.4.3, @react-stately/flags@3.0.4, @react-stately/form@3.0.6, @react-stately/grid@3.9.3, @react-stately/list@3.11.0, @react-stately/menu@3.8.3, @react-stately/numberfield@3.9.7, @react-stately/overlays@3.6.11, @react-stately/radio@3.10.8, @react-stately/searchfield@3.5.7, @react-stately/select@3.6.8, @react-stately/selection@3.17.0, @react-stately/slider@3.5.8, @react-stately/table@3.12.3, @react-stately/tabs@3.6.10, @react-stately/toggle@3.7.8, @react-stately/tooltip@3.4.13, @react-stately/tree@3.8.5, @react-stately/utils@3.10.4, @react-types/breadcrumbs@3.7.8, @react-types/button@3.10.0, @react-types/calendar@3.4.10, @react-types/checkbox@3.8.4, @react-types/color@3.0.0, @react-types/combobox@3.13.0, @react-types/datepicker@3.8.3, @react-types/dialog@3.5.13, @react-types/grid@3.2.9, @react-types/link@3.5.8, @react-types/listbox@3.5.2, @react-types/menu@3.9.12, @react-types/meter@3.4.4, @react-types/numberfield@3.8.6, @react-types/overlays@3.8.10, @react-types/progress@3.5.7, @react-types/radio@3.8.4, @react-types/searchfield@3.5.9, @react-types/select@3.9.7, @react-types/shared@3.25.0, @react-types/slider@3.7.6, @react-types/switch@3.5.6, @react-types/table@3.10.2, @react-types/tabs@3.3.10, @react-types/textfield@3.9.7, @react-types/tooltip@3.4.12, lerc@3.0.0, react-aria@3.35.0
Apache-2.0

color-rgba@3.0.0, javascript-natural-sort@0.7.1, react-select@5.8.1, seedrandom@3.0.5
MIT

openapi-zod-client@1.18.2
ISC
```

**Comment by tobysmith568** [comment]
Hey @jayvdb,

> My guess is that the dependency defines the license in package.json, but the LICENSE file is missing or couldnt be found.

Yeah this is usually exactly right, and we share your frustrations here. That said, we think it's important that we don't speak on behalf of a library author. By taking the (somewhat) vague SPDX expression from the package.json and trying to download/fetch the equivalent license content we'd be guessing at what their intentions are - which something that we don't want to do.

Our stance is that we can only be as precise as the library authors themselves. If there are packages out there that you want more precise licenses for then we encourage you to reach out to their authors asking them to publish the license files as a part of their packages... It's what they should be doing anyway.

Happy to re-open if we've misunderstood what you're asking for in any way.

**Comment by jayvdb** [comment]
Thanks for your reply @tobysmith568 .

First I would like to address this

> By taking the (somewhat) vague SPDX expression from the package.json ..

@SPDX is not vague.  It has specifications, and it is a controlled vocabulary.

Probably you are aware of this, and that is why you said "somewhat", but this triggered me.

If someone has used an invalid SPDX identifier in their published package, that should be rejected, and fixed upstream urgently.  It isnt helped in Node world that npmjs registry has not had any rules about the schema of `package.json` being uploaded, so the metadata in packages varies quite a bit.  But that isnt the fault of SPDX, and the vast majority of packages have valid SPDX identifiers.

I have been involved in fixing packages like this in many language ecosystems.  I've been involved in fixing metadata like this in Python, Node and even Rust ecosystem. And because I have been actively fixing upstream metadata for over 10 years, I know this strategy is unsatisfactory, especially for Node.

For example, https://www.npmjs.com/package/callsite was released 12 years ago, has 558 packages that depends on it, and has shocking metadata.  There are merged PRs in the repo https://github.com/tj/callsite/commits/master/ , but it isnt released.  https://www.npmjs.com/package/exit is similar.  https://github.com/ericf/css-mediaquery/pull/23 is another.

And that is metadata.  Getting authors/maintainers to add LICENSE files to their repo is even harder, and again even harder to get a published package with the LICENSE file included.

I'll partially address https://github.com/TobyAndToby/generate-license-file/issues/526 briefly here as well.  Even if a LICENSE file is included in the package, often it is is incomplete.  Even for a simple license like [MIT](https://spdx.org/licenses/MIT.html), the license says "The above copyright notice ", and that is often missing, incomplete, or mangled.  Authors and maintainers often do not see the value of this type of PR.

App developers that are wanting to comply with licensing terms (unfortunately quite rare), and wishing to be an advocate for OSS, want to provide their users with a pretty and accurate license page.  Having some entries show a license text, and others showing only a SPDX identifier, is not a nice UX.  Also only showing an SPDX identifier is not even trying to comply with the terms of the license.

Typically app developers do not have the time, interest, and knowledge required to fix the problems upstream in order to achieve a pretty and accurate license page.  A tool like `generate-license-file` can bridge that gap, by making it easy to achieve what the app developer and the user desires, while also advising the app developer when they can help their upstreams.

I can appreciate that a tool like this should avoid automatically doing things that are based on guessing.
However that can be addressed by having an opt-in flag for doing extra steps, appropriately named and described to reduce misuse, and relying on the tool user to verify its work.  And there are already mechanisms in the tool config for overriding the tool on a per-package level where the tool user has a better solution than the tool can produce.

To drill in a bit, I have 41 packages associated with the 'content' of "Apache-2.0", and 6 associated with "MIT".  And over time those lists will change, with new ones added and others dropping off.  But I hope you can see that having to add and maintain overrides for 47 entries is not ideal, and fixing those upstream is going to be a significant undertaking, and likely it is blocked by one of them - and it only takes one of them to cause my UX to have these weird entries.  I *know* that the Apache-2.0 license file contents should never be different from the Apache 2.0 license text, as that license is structured so that there are no placeholders in the license text - the placeholders are in the NOTICE file which should also be added.  The MIT license isnt as simple, as the license file does contain placeholders, however I know there are libraries which can be given `(spdx, author name, current year)` and they generate a LICENSE file.

If the team here is really firm on rejecting this requested feature, I would instead recommend that `generate-license-file` emits a warning or error when it encounters this situation, *and* not ever emit a entry where "content" is just the SPDX identifier, because it is *surprising* that this tool would put "Apache 2.0" as a license text, as that is not a license text.  I would opt for it being an error, so the tool user is required to add a `replace` or `exclude` to proceed, and then the result is the tool users intentions, not the tool itself falling back to using a `package.json` field.

**Comment by jayvdb** [comment]
One extra point I wanted to note, https://github.com/jslicense/licensee.js has a "corrections" flag which activates using  https://github.com/jslicense/npm-license-corrections.json to auto-fix problems in package metadata.
