### ISSUE TITLE
Include NOTICE for Apache-2.0

### ISSUE THREAD

**Issue by jayvdb** [TobyAndToby/generate-license-file#529]
**Describe the bug**
https://www.apache.org/licenses/LICENSE-2.0.html#redistribution says:

> If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file ...

This is the first three lines of https://github.com/josdejong/mathjs/blob/develop/NOTICE

Another example https://github.com/nodejs/import-in-the-middle/blob/main/NOTICE

**How are you using generate-license-file?**
Library

**What version of generate-license-file are you using?**
3.5.1

**To Reproduce**

Run this tool on a project depending on https://www.npmjs.com/package/mathjs

**Expected behavior**

The NOTICE file should be included, or at least the lines of the NOTICE file that are unique to each project.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tobysmith568** [comment]
Hey @jayvdb,

In the past we've worked on the assumption that a consumer of a package would only want/need a single file - either a `LICENSE.md` or a `NOTICE.md`. However we've now drawn the conclusion that, yeah, it can often be important to include both. In PR #543 we've made notice files a first-class feature of our `ILicense` interface. We'll be releasing this feature shortly.

**Comment by tobysmith568** [comment]
Hey @jayvdb,

This has gone out in version 3.6.0!

I'm going to close this for now - let us know here or open a new issue if you have any issues.

Thanks

**Comment by jayvdb** [comment]
Thank you @tobysmith568 , we are now utilising this new feature.  Much appreciated.
