### ISSUE TITLE
Programmatic use =>Many errors

### ISSUE THREAD

**Issue by aminkosh** [TobyAndToby/generate-license-file#8]
Hi,
If I want to use the "Programmatic use" way, i get the following errors:
Could you please help me to solve the problem?

Warning: ./node_modules/minimatch/minimatch.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\minimatch'

Warning: C:\DEV\Grund_DevOpsGlobal\angular\src\AppPreBootstrap.ts depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\DEV\Grund_DevOpsGlobal\angular\src\assets\metronic\app\core\directives\menu-aside.directive.ts depends on 'object-path'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\DEV\Grund_DevOpsGlobal\angular\src\app\main\main.module.ts depends on 'angular2-counto'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\DEV\Grund_DevOpsGlobal\angular\src\app\admin\admin.module.ts depends on 'angular2-text-mask'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Error: ./node_modules/graceful-fs/polyfills.js
Module not found: Error: Can't resolve 'constants' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\graceful-fs'

Error: ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\fs.realpath'

Error: ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\fs.realpath'

Error: ./node_modules/generate-license-file/dist/utils/file.utils.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\generate-license-file\dist\utils'

Error: ./node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\glob'

Error: ./node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\glob'

Error: ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\graceful-fs'

Error: ./node_modules/license-checker/lib/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\license-checker\lib'

Error: ./node_modules/license-checker/node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\license-checker\node_modules\mkdirp'

Error: ./node_modules/read-installed/read-installed.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\read-installed'

Error: ./node_modules/read-package-json/read-json.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\read-package-json'

Error: ./node_modules/resolve/lib/async.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\resolve\lib'

Error: ./node_modules/resolve/lib/sync.js
Module not found: Error: Can't resolve 'fs' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\resolve\lib'

Error: ./node_modules/generate-license-file/dist/main.js
Module not found: Error: Can't resolve 'os' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\generate-license-file\dist'

Error: ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\fs.realpath'

Error: ./node_modules/glob/glob.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\glob'

Error: ./node_modules/glob/common.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\glob'

Error: ./node_modules/glob/sync.js
1mModule not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\glob'

Error: ./node_modules/license-checker/lib/index.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\license-checker\lib'

Error: ./node_modules/license-checker/lib/license-files.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\license-checker\lib'

Error: ./node_modules/license-checker/node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\license-checker\node_modules\mkdirp'

Error: ./node_modules/npm-normalize-package-bin/index.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\npm-normalize-package-bin'

Error: ./node_modules/read-installed/read-installed.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\read-installed'

Error: ./node_modules/read-package-json/read-json.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\read-package-json'

Error: ./node_modules/readdir-scoped-modules/readdir.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\readdir-scoped-modules'

Error: ./node_modules/resolve/lib/async.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\resolve\lib'

Error: ./node_modules/resolve/lib/sync.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\resolve\lib'

Error: ./node_modules/resolve/lib/node-modules-paths.js
Module not found: Error: Can't resolve 'path' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\resolve\lib'

Error: ./node_modules/spdx-expression-parse/scan.js
Module not found: Error: Can't resolve 'spdx-exceptions' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\spdx-expression-parse'

Error: ./node_modules/spdx-correct/index.js
Module not found: Error: Can't resolve 'spdx-license-ids' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\spdx-correct'

Error: ./node_modules/spdx-expression-parse/scan.js
Module not found: Error: Can't resolve 'spdx-license-ids' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\spdx-expression-parse'

Error: ./node_modules/spdx-expression-parse/scan.js
Module not found: Error: Can't resolve 'spdx-license-ids/deprecated' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\spdx-expression-parse'

Error: ./node_modules/spdx-compare/index.js
Module not found: Error: Can't resolve 'spdx-ranges' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\spdx-compare'

Error: ./node_modules/spdx-satisfies/index.js
Module not found: Error: Can't resolve 'spdx-ranges' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\spdx-satisfies'

Error: ./node_modules/graceful-fs/legacy-streams.js
Module not found: Error: Can't resolve 'stream' in 'C:\DEV\Grund_DevOpsGlobal\angular\node_modules\graceful-fs'

** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'

**Comment by tobysmith568** [comment]
Hey :)

It looks like you're using this library inside an Angular application - is that the case?

This library requires access to the file system of the computer which is generally not something you can do from websites.
In your specific instance the code is trying to use the 'path' module, and that's one of the ones which node processes can use but websites cannot.

If you provide more context for what you're trying to do, and possibly provide some code for how you're doing it, then we might be able to help more :)

**Comment by aminkosh** [comment]
Hi,
Exactly. I juts use it in angular and after installing the package i can import the module like this:
`const generateLicenseFile = require("generate-license-file");`
or
`import * as generateLicenseFile from "generate-license-file";
`
But whenever i want to use it:
`show()
{
generateLicenseFile
  .getProjectLicenses("./")
  .then(licenses => {
   alert(licenses );
  })
  .catch(error => {
    // do stuff with error...
  });
}
`
 I get compile errors

**Comment by tobysmith568** [comment]
Solved with #9
