### ISSUE TITLE
Illegal operation on a directory

### ISSUE THREAD

**Issue by aminkosh** [TobyAndToby/generate-license-file#9]
Hi,
In Angular whenever i try to create the license file in sub folder (here src) 
`>generate-license-file --input package.json --output src 3rd-party-licenses.txt`
I got this error. 
Error: EISDIR: illegal operation on a directory, open 'C:\DEV\DAC6\angular\src'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: 'C:\\DEV\\DAC6\\angular\\src'
}
It works only if i create the file in same folder (not set the path)
`generate-license-file --input package.json --output 3rd-party-licenses.txt`

Any help appreciated.

**Comment by tobysmith568** [comment]
The output option needs to be a path separated by slashes, not spaces

`generate-license-file --input package.json --output src/3rd-party-licenses.txt`

**Comment by aminkosh** [comment]
since you solved my problem here , the other approach (issue) is no longer needed.
Thank you very much.

**Comment by tobysmith568** [comment]
Cool, I'll close it then. Happy to have helped :)
